#!/usr/bin/env python3
"""tools/fetch_fonts.py - vendor the web fonts into static/fonts/.

    python tools/fetch_fonts.py [--check]

The app is local-first ("nothing is uploaded"), but its fonts used to come from
fonts.googleapis.com - so on a machine with no internet every page silently
dropped to system faces and the whole UI changed shape. This downloads the
families once, writes static/fonts.css with the same unicode-range subsetting
Google serves, and points the @font-face rules at local files.

Run it when a family or weight range changes. The output is committed: these
are SIL Open Font License faces, so redistributing them with the app is exactly
what the licence is for (unlike static/assets/, which is Valve content and
stays gitignored).

--check re-fetches the stylesheets and reports whether the vendored CSS is
still current, without writing anything.
"""
import argparse
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FONT_DIR = os.path.join(ROOT, 'static', 'fonts')
CSS_PATH = os.path.join(ROOT, 'static', 'fonts.css')

# A real browser UA is required: the Google Fonts CSS API serves woff2 only to
# clients it believes support it, and falls back to bloated legacy formats
# (or refuses) otherwise.
UA = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')

# (family spec, local filename stem). Weight ranges are variable-font axes, so
# each family is ONE file per subset rather than one per weight.
FAMILIES = [
    ('Archivo:wght@400..800',        'archivo'),
    ('Archivo+Narrow:wght@400..700', 'archivo-narrow'),
    ('Roboto+Mono:wght@400..700',    'roboto-mono'),
]

HEADER = """/*
 * static/fonts.css - GENERATED by tools/fetch_fonts.py. Do not edit by hand.
 *
 * Self-hosted so the app works with no network, which the rest of it already
 * assumes. Subsets and unicode-ranges are Google's own, kept as-is so a browser
 * still downloads only the ranges a page actually uses.
 *
 * Coverage note, load-bearing for player names: Archivo and Archivo Narrow are
 * Latin/Latin-Ext/Vietnamese ONLY - no Cyrillic, no Greek, no CJK. Roboto Mono
 * adds Cyrillic and Greek. Steam names routinely contain all of those, so the
 * --font-* stacks in _shell.html end in system-ui deliberately: a non-Latin
 * name renders in the platform UI face by design, not by accident.
 */
"""


def fetch(url):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def build(check_only=False):
    os.makedirs(FONT_DIR, exist_ok=True)
    chunks, downloaded, seen = [HEADER], 0, set()

    for spec, stem in FAMILIES:
        css = fetch(f'https://fonts.googleapis.com/css2?family={spec}&display=swap').decode('utf-8')
        subset = 'unknown'

        def sub_url(m):
            nonlocal downloaded
            url = m.group(1)
            name = f'{stem}-{subset}.woff2'
            dest = os.path.join(FONT_DIR, name)
            if name not in seen:
                seen.add(name)
                if not check_only and not os.path.isfile(dest):
                    with open(dest, 'wb') as f:
                        f.write(fetch(url))
                    downloaded += 1
            return f"url('fonts/{name}')"

        out = []
        for line in css.splitlines():
            c = re.match(r'^/\*\s*(\S+)\s*\*/$', line.strip())
            if c:
                subset = c.group(1)
            out.append(re.sub(r"url\((https://[^)]+)\)", sub_url, line))
        chunks.append('\n'.join(out))

    css_text = '\n'.join(chunks) + '\n'
    if check_only:
        cur = open(CSS_PATH, encoding='utf-8').read() if os.path.isfile(CSS_PATH) else ''
        same = (cur == css_text)
        missing = [n for n in seen if not os.path.isfile(os.path.join(FONT_DIR, n))]
        print('fonts.css up to date' if same else 'fonts.css DIFFERS from upstream')
        if missing:
            print('missing files:', ', '.join(sorted(missing)))
        return 0 if (same and not missing) else 1

    with open(CSS_PATH, 'w', encoding='utf-8', newline='\n') as f:
        f.write(css_text)
    total = sum(os.path.getsize(os.path.join(FONT_DIR, n)) for n in seen)
    print(f'{len(seen)} font file(s), {downloaded} newly downloaded, {total/1024:.0f} KB total')
    print(f'wrote {CSS_PATH}')
    return 0


if __name__ == '__main__':
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--check', action='store_true',
                    help='report whether the vendored CSS matches upstream; write nothing')
    sys.exit(build(ap.parse_args().check))
